SELECT `TABLE_NAME`, `ENGINE`, `AUTO_INCREMENT`, `TABLE_COMMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB');

CREATE TABLE IF NOT EXISTS `user` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `lower_name` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `full_name` VARCHAR(255) NULL, `email` VARCHAR(255) NOT NULL, `keep_email_private` TINYINT(1) NULL, `email_notifications_preference` VARCHAR(20) DEFAULT 'enabled' NOT NULL, `passwd` VARCHAR(255) NOT NULL, `passwd_hash_algo` VARCHAR(255) DEFAULT 'pbkdf2' NOT NULL, `must_change_password` TINYINT(1) DEFAULT false NOT NULL, `login_type` INT NULL, `login_source` BIGINT(20) DEFAULT 0 NOT NULL, `login_name` VARCHAR(255) NULL, `type` INT NULL, `location` VARCHAR(255) NULL, `website` VARCHAR(255) NULL, `rands` VARCHAR(10) NULL, `salt` VARCHAR(10) NULL, `language` VARCHAR(5) NULL, `description` VARCHAR(255) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL, `last_login_unix` BIGINT(20) NULL, `last_repo_visibility` TINYINT(1) NULL, `max_repo_creation` INT DEFAULT -1 NOT NULL, `is_active` TINYINT(1) NULL, `is_admin` TINYINT(1) NULL, `is_restricted` TINYINT(1) DEFAULT false NOT NULL, `allow_git_hook` TINYINT(1) NULL, `allow_import_local` TINYINT(1) NULL, `allow_create_organization` TINYINT(1) DEFAULT true NULL, `prohibit_login` TINYINT(1) DEFAULT false NOT NULL, `avatar` VARCHAR(2048) NOT NULL, `avatar_email` VARCHAR(255) NOT NULL, `use_custom_avatar` TINYINT(1) NULL, `num_followers` INT NULL, `num_following` INT DEFAULT 0 NOT NULL, `num_stars` INT NULL, `num_repos` INT NULL, `num_teams` INT NULL, `num_members` INT NULL, `visibility` INT DEFAULT 0 NOT NULL, `repo_admin_change_team_access` TINYINT(1) DEFAULT false NOT NULL, `diff_view_style` VARCHAR(255) DEFAULT '' NOT NULL, `theme` VARCHAR(255) DEFAULT '' NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_user_lower_name` ON `user` (`lower_name`);
CREATE UNIQUE INDEX `UQE_user_name` ON `user` (`name`);
CREATE INDEX `IDX_user_is_active` ON `user` (`is_active`);
CREATE INDEX `IDX_user_created_unix` ON `user` (`created_unix`);
CREATE INDEX `IDX_user_updated_unix` ON `user` (`updated_unix`);
CREATE INDEX `IDX_user_last_login_unix` ON `user` (`last_login_unix`);
CREATE TABLE IF NOT EXISTS `public_key` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `owner_id` BIGINT(20) NOT NULL, `name` VARCHAR(255) NOT NULL, `fingerprint` VARCHAR(255) NOT NULL, `content` TEXT NOT NULL, `mode` INT DEFAULT 2 NOT NULL, `type` INT DEFAULT 1 NOT NULL, `login_source_id` BIGINT(20) DEFAULT 0 NOT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_public_key_fingerprint` ON `public_key` (`fingerprint`);
CREATE INDEX `IDX_public_key_owner_id` ON `public_key` (`owner_id`);
CREATE TABLE IF NOT EXISTS `access_token` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `token_hash` VARCHAR(255) NULL, `token_salt` VARCHAR(255) NULL, `token_last_eight` VARCHAR(255) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_access_token_token_hash` ON `access_token` (`token_hash`);
CREATE INDEX `IDX_access_token_uid` ON `access_token` (`uid`);
CREATE INDEX `IDX_access_token_created_unix` ON `access_token` (`created_unix`);
CREATE INDEX `IDX_access_token_updated_unix` ON `access_token` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `repository` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `owner_id` BIGINT(20) NULL, `owner_name` VARCHAR(255) NULL, `lower_name` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `description` TEXT NULL, `website` VARCHAR(2048) NULL, `original_service_type` INT NULL, `original_url` VARCHAR(2048) NULL, `default_branch` VARCHAR(255) NULL, `num_watches` INT NULL, `num_stars` INT NULL, `num_forks` INT NULL, `num_issues` INT NULL, `num_closed_issues` INT NULL, `num_pulls` INT NULL, `num_closed_pulls` INT NULL, `num_milestones` INT DEFAULT 0 NOT NULL, `num_closed_milestones` INT DEFAULT 0 NOT NULL, `is_private` TINYINT(1) NULL, `is_empty` TINYINT(1) NULL, `is_archived` TINYINT(1) NULL, `is_mirror` TINYINT(1) NULL, `status` INT DEFAULT 0 NOT NULL, `is_fork` TINYINT(1) DEFAULT false NOT NULL, `fork_id` BIGINT(20) NULL, `is_template` TINYINT(1) DEFAULT false NOT NULL, `template_id` BIGINT(20) NULL, `size` BIGINT(20) DEFAULT 0 NOT NULL, `is_fsck_enabled` TINYINT(1) DEFAULT true NOT NULL, `close_issues_via_commit_in_any_branch` TINYINT(1) DEFAULT false NOT NULL, `topics` TEXT NULL, `avatar` VARCHAR(64) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_repository_s` ON `repository` (`owner_id`,`lower_name`);
CREATE INDEX `IDX_repository_lower_name` ON `repository` (`lower_name`);
CREATE INDEX `IDX_repository_is_template` ON `repository` (`is_template`);
CREATE INDEX `IDX_repository_created_unix` ON `repository` (`created_unix`);
CREATE INDEX `IDX_repository_original_service_type` ON `repository` (`original_service_type`);
CREATE INDEX `IDX_repository_is_private` ON `repository` (`is_private`);
CREATE INDEX `IDX_repository_is_empty` ON `repository` (`is_empty`);
CREATE INDEX `IDX_repository_is_mirror` ON `repository` (`is_mirror`);
CREATE INDEX `IDX_repository_is_archived` ON `repository` (`is_archived`);
CREATE INDEX `IDX_repository_is_fork` ON `repository` (`is_fork`);
CREATE INDEX `IDX_repository_updated_unix` ON `repository` (`updated_unix`);
CREATE INDEX `IDX_repository_owner_id` ON `repository` (`owner_id`);
CREATE INDEX `IDX_repository_name` ON `repository` (`name`) ;
CREATE INDEX `IDX_repository_fork_id` ON `repository` (`fork_id`);
CREATE INDEX `IDX_repository_template_id` ON `repository` (`template_id`);
CREATE TABLE IF NOT EXISTS `deploy_key` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `key_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `fingerprint` VARCHAR(255) NULL, `mode` INT DEFAULT 1 NOT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_deploy_key_s` ON `deploy_key` (`key_id`,`repo_id`);
CREATE INDEX `IDX_deploy_key_key_id` ON `deploy_key` (`key_id`);
CREATE INDEX `IDX_deploy_key_repo_id` ON `deploy_key` (`repo_id`);
CREATE TABLE IF NOT EXISTS `collaboration` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NOT NULL, `user_id` BIGINT(20) NOT NULL, `mode` INT DEFAULT 2 NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_collaboration_s` ON `collaboration` (`repo_id`,`user_id`);
CREATE INDEX `IDX_collaboration_user_id` ON `collaboration` (`user_id`);
CREATE INDEX `IDX_collaboration_repo_id` ON `collaboration` (`repo_id`);
CREATE TABLE IF NOT EXISTS `access` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `mode` INT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_access_s` ON `access` (`user_id`,`repo_id`);
CREATE TABLE IF NOT EXISTS `upload` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uuid` VARCHAR(40) NULL, `name` VARCHAR(255) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_upload_uuid` ON `upload` (`uuid`);
CREATE TABLE IF NOT EXISTS `watch` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `mode` SMALLINT DEFAULT 1 NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_watch_watch` ON `watch` (`user_id`,`repo_id`);
CREATE TABLE IF NOT EXISTS `star` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_star_s` ON `star` (`uid`,`repo_id`);
CREATE TABLE IF NOT EXISTS `follow` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NULL, `follow_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_follow_follow` ON `follow` (`user_id`,`follow_id`);
CREATE TABLE IF NOT EXISTS `action` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NULL, `op_type` INT NULL, `act_user_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `comment_id` BIGINT(20) NULL, `is_deleted` TINYINT(1) DEFAULT false NOT NULL, `ref_name` VARCHAR(255) NULL, `is_private` TINYINT(1) DEFAULT false NOT NULL, `content` TEXT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_action_is_deleted` ON `action` (`is_deleted`);
CREATE INDEX `IDX_action_is_private` ON `action` (`is_private`);
CREATE INDEX `IDX_action_created_unix` ON `action` (`created_unix`);
CREATE INDEX `IDX_action_user_id` ON `action` (`user_id`);
CREATE INDEX `IDX_action_act_user_id` ON `action` (`act_user_id`);
CREATE INDEX `IDX_action_repo_id` ON `action` (`repo_id`);
CREATE INDEX `IDX_action_comment_id` ON `action` (`comment_id`);
CREATE TABLE IF NOT EXISTS `issue` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `index` BIGINT(20) NULL, `poster_id` BIGINT(20) NULL, `original_author` VARCHAR(255) NULL, `original_author_id` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `content` TEXT NULL, `milestone_id` BIGINT(20) NULL, `priority` INT NULL, `is_closed` TINYINT(1) NULL, `is_pull` TINYINT(1) NULL, `num_comments` INT NULL, `ref` VARCHAR(255) NULL, `deadline_unix` BIGINT(20) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL, `closed_unix` BIGINT(20) NULL, `is_locked` TINYINT(1) DEFAULT false NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_issue_repo_index` ON `issue` (`repo_id`,`index`);
CREATE INDEX `IDX_issue_poster_id` ON `issue` (`poster_id`);
CREATE INDEX `IDX_issue_is_closed` ON `issue` (`is_closed`);
CREATE INDEX `IDX_issue_is_pull` ON `issue` (`is_pull`);
CREATE INDEX `IDX_issue_updated_unix` ON `issue` (`updated_unix`);
CREATE INDEX `IDX_issue_repo_id` ON `issue` (`repo_id`);
CREATE INDEX `IDX_issue_original_author_id` ON `issue` (`original_author_id`);
CREATE INDEX `IDX_issue_milestone_id` ON `issue` (`milestone_id`);
CREATE INDEX `IDX_issue_deadline_unix` ON `issue` (`deadline_unix`);
CREATE INDEX `IDX_issue_created_unix` ON `issue` (`created_unix`);
CREATE INDEX `IDX_issue_closed_unix` ON `issue` (`closed_unix`);
CREATE TABLE IF NOT EXISTS `pull_request` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` INT NULL, `status` INT NULL, `conflicted_files` TEXT NULL, `commits_ahead` INT NULL, `commits_behind` INT NULL, `issue_id` BIGINT(20) NULL, `index` BIGINT(20) NULL, `head_repo_id` BIGINT(20) NULL, `base_repo_id` BIGINT(20) NULL, `head_branch` VARCHAR(255) NULL, `base_branch` VARCHAR(255) NULL, `merge_base` VARCHAR(40) NULL, `has_merged` TINYINT(1) NULL, `merged_commit_id` VARCHAR(40) NULL, `merger_id` BIGINT(20) NULL, `merged_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_pull_request_merged_unix` ON `pull_request` (`merged_unix`);
CREATE INDEX `IDX_pull_request_issue_id` ON `pull_request` (`issue_id`);
CREATE INDEX `IDX_pull_request_head_repo_id` ON `pull_request` (`head_repo_id`);
CREATE INDEX `IDX_pull_request_base_repo_id` ON `pull_request` (`base_repo_id`);
CREATE INDEX `IDX_pull_request_has_merged` ON `pull_request` (`has_merged`);
CREATE INDEX `IDX_pull_request_merger_id` ON `pull_request` (`merger_id`);
CREATE TABLE IF NOT EXISTS `comment` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` INT NULL, `poster_id` BIGINT(20) NULL, `original_author` VARCHAR(255) NULL, `original_author_id` BIGINT(20) NULL, `issue_id` BIGINT(20) NULL, `label_id` BIGINT(20) NULL, `old_milestone_id` BIGINT(20) NULL, `milestone_id` BIGINT(20) NULL, `assignee_id` BIGINT(20) NULL, `removed_assignee` TINYINT(1) NULL, `resolve_doer_id` BIGINT(20) NULL, `old_title` VARCHAR(255) NULL, `new_title` VARCHAR(255) NULL, `old_ref` VARCHAR(255) NULL, `new_ref` VARCHAR(255) NULL, `dependent_issue_id` BIGINT(20) NULL, `commit_id` BIGINT(20) NULL, `line` BIGINT(20) NULL, `tree_path` VARCHAR(255) NULL, `content` TEXT NULL, `patch` TEXT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL, `commit_sha` VARCHAR(40) NULL, `review_id` BIGINT(20) NULL, `invalidated` TINYINT(1) NULL, `ref_repo_id` BIGINT(20) NULL, `ref_issue_id` BIGINT(20) NULL, `ref_comment_id` BIGINT(20) NULL, `ref_action` SMALLINT NULL, `ref_is_pull` TINYINT(1) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_comment_review_id` ON `comment` (`review_id`);
CREATE INDEX `IDX_comment_ref_repo_id` ON `comment` (`ref_repo_id`);
CREATE INDEX `IDX_comment_ref_issue_id` ON `comment` (`ref_issue_id`);
CREATE INDEX `IDX_comment_type` ON `comment` (`type`);
CREATE INDEX `IDX_comment_poster_id` ON `comment` (`poster_id`);
CREATE INDEX `IDX_comment_created_unix` ON `comment` (`created_unix`);
CREATE INDEX `IDX_comment_updated_unix` ON `comment` (`updated_unix`);
CREATE INDEX `IDX_comment_issue_id` ON `comment` (`issue_id`);
CREATE INDEX `IDX_comment_ref_comment_id` ON `comment` (`ref_comment_id`);
CREATE TABLE IF NOT EXISTS `attachment` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uuid` VARCHAR(40) NULL, `issue_id` BIGINT(20) NULL, `release_id` BIGINT(20) NULL, `uploader_id` BIGINT(20) DEFAULT 0 NULL, `comment_id` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `download_count` BIGINT(20) DEFAULT 0 NULL, `size` BIGINT(20) DEFAULT 0 NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_attachment_uuid` ON `attachment` (`uuid`);
CREATE INDEX `IDX_attachment_uploader_id` ON `attachment` (`uploader_id`);
CREATE INDEX `IDX_attachment_issue_id` ON `attachment` (`issue_id`);
CREATE INDEX `IDX_attachment_release_id` ON `attachment` (`release_id`);
CREATE TABLE IF NOT EXISTS `label` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `org_id` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `description` VARCHAR(255) NULL, `color` VARCHAR(7) NULL, `num_issues` INT NULL, `num_closed_issues` INT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_label_repo_id` ON `label` (`repo_id`);
CREATE INDEX `IDX_label_org_id` ON `label` (`org_id`);
CREATE TABLE IF NOT EXISTS `issue_label` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `issue_id` BIGINT(20) NULL, `label_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_issue_label_s` ON `issue_label` (`issue_id`,`label_id`);
CREATE TABLE IF NOT EXISTS `milestone` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `content` TEXT NULL, `is_closed` TINYINT(1) NULL, `num_issues` INT NULL, `num_closed_issues` INT NULL, `completeness` INT NULL, `deadline_unix` BIGINT(20) NULL, `closed_date_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_milestone_repo_id` ON `milestone` (`repo_id`);
CREATE TABLE IF NOT EXISTS `mirror` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `interval` BIGINT(20) NULL, `enable_prune` TINYINT(1) DEFAULT true NOT NULL, `updated_unix` BIGINT(20) NULL, `next_update_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_mirror_repo_id` ON `mirror` (`repo_id`);
CREATE INDEX `IDX_mirror_updated_unix` ON `mirror` (`updated_unix`);
CREATE INDEX `IDX_mirror_next_update_unix` ON `mirror` (`next_update_unix`);
CREATE TABLE IF NOT EXISTS `release` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `publisher_id` BIGINT(20) NULL, `tag_name` VARCHAR(255) NULL, `original_author` VARCHAR(255) NULL, `original_author_id` BIGINT(20) NULL, `lower_tag_name` VARCHAR(255) NULL, `target` VARCHAR(255) NULL, `title` VARCHAR(255) NULL, `sha1` VARCHAR(40) NULL, `num_commits` BIGINT(20) NULL, `note` TEXT NULL, `is_draft` TINYINT(1) DEFAULT false NOT NULL, `is_prerelease` TINYINT(1) DEFAULT false NOT NULL, `is_tag` TINYINT(1) DEFAULT false NOT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_release_n` ON `release` (`repo_id`,`tag_name`);
CREATE INDEX `IDX_release_repo_id` ON `release` (`repo_id`);
CREATE INDEX `IDX_release_publisher_id` ON `release` (`publisher_id`);
CREATE INDEX `IDX_release_tag_name` ON `release` (`tag_name`);
CREATE INDEX `IDX_release_original_author_id` ON `release` (`original_author_id`);
CREATE INDEX `IDX_release_created_unix` ON `release` (`created_unix`);
CREATE TABLE IF NOT EXISTS `login_source` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` INT NULL, `name` VARCHAR(255) NULL, `is_actived` TINYINT(1) DEFAULT false NOT NULL, `is_sync_enabled` TINYINT(1) DEFAULT false NOT NULL, `cfg` TEXT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_login_source_name` ON `login_source` (`name`);
CREATE INDEX `IDX_login_source_created_unix` ON `login_source` (`created_unix`);
CREATE INDEX `IDX_login_source_updated_unix` ON `login_source` (`updated_unix`);
CREATE INDEX `IDX_login_source_is_actived` ON `login_source` (`is_actived`);
CREATE INDEX `IDX_login_source_is_sync_enabled` ON `login_source` (`is_sync_enabled`);
CREATE TABLE IF NOT EXISTS `webhook` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `org_id` BIGINT(20) NULL, `is_system_webhook` TINYINT(1) NULL, `url` TEXT NULL, `signature` TEXT NULL, `http_method` VARCHAR(255) NULL, `content_type` INT NULL, `secret` TEXT NULL, `events` TEXT NULL, `is_ssl` TINYINT(1) NULL, `is_active` TINYINT(1) NULL, `hook_task_type` INT NULL, `meta` TEXT NULL, `last_status` INT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_webhook_org_id` ON `webhook` (`org_id`);
CREATE INDEX `IDX_webhook_is_active` ON `webhook` (`is_active`);
CREATE INDEX `IDX_webhook_created_unix` ON `webhook` (`created_unix`);
CREATE INDEX `IDX_webhook_updated_unix` ON `webhook` (`updated_unix`);
CREATE INDEX `IDX_webhook_repo_id` ON `webhook` (`repo_id`);
CREATE TABLE IF NOT EXISTS `hook_task` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `hook_id` BIGINT(20) NULL, `uuid` VARCHAR(255) NULL, `type` INT NULL, `url` TEXT NULL, `signature` TEXT NULL, `payload_content` TEXT NULL, `http_method` VARCHAR(255) NULL, `content_type` INT NULL, `event_type` VARCHAR(255) NULL, `is_ssl` TINYINT(1) NULL, `is_delivered` TINYINT(1) NULL, `delivered` BIGINT(20) NULL, `is_succeed` TINYINT(1) NULL, `request_content` TEXT NULL, `response_content` TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_hook_task_repo_id` ON `hook_task` (`repo_id`);
CREATE TABLE IF NOT EXISTS `team` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `org_id` BIGINT(20) NULL, `lower_name` VARCHAR(255) NULL, `name` VARCHAR(255) NULL, `description` VARCHAR(255) NULL, `authorize` INT NULL, `num_repos` INT NULL, `num_members` INT NULL, `includes_all_repositories` TINYINT(1) DEFAULT false NOT NULL, `can_create_org_repo` TINYINT(1) DEFAULT false NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_team_org_id` ON `team` (`org_id`);
CREATE TABLE IF NOT EXISTS `org_user` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `org_id` BIGINT(20) NULL, `is_public` TINYINT(1) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_org_user_s` ON `org_user` (`uid`,`org_id`);
CREATE INDEX `IDX_org_user_uid` ON `org_user` (`uid`);
CREATE INDEX `IDX_org_user_org_id` ON `org_user` (`org_id`);
CREATE INDEX `IDX_org_user_is_public` ON `org_user` (`is_public`);
CREATE TABLE IF NOT EXISTS `team_user` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `org_id` BIGINT(20) NULL, `team_id` BIGINT(20) NULL, `uid` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_team_user_s` ON `team_user` (`team_id`,`uid`);
CREATE INDEX `IDX_team_user_org_id` ON `team_user` (`org_id`);
CREATE TABLE IF NOT EXISTS `team_repo` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `org_id` BIGINT(20) NULL, `team_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_team_repo_s` ON `team_repo` (`team_id`,`repo_id`);
CREATE INDEX `IDX_team_repo_org_id` ON `team_repo` (`org_id`);
CREATE TABLE IF NOT EXISTS `notice` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` INT NULL, `description` TEXT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_notice_created_unix` ON `notice` (`created_unix`);
CREATE TABLE IF NOT EXISTS `email_address` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NOT NULL, `email` VARCHAR(255) NOT NULL, `is_activated` TINYINT(1) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_email_address_email` ON `email_address` (`email`);
CREATE INDEX `IDX_email_address_uid` ON `email_address` (`uid`);
CREATE TABLE IF NOT EXISTS `notification` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NOT NULL, `repo_id` BIGINT(20) NOT NULL, `status` SMALLINT NOT NULL, `source` SMALLINT NOT NULL, `issue_id` BIGINT(20) NOT NULL, `commit_id` VARCHAR(255) NULL, `comment_id` BIGINT(20) NULL, `updated_by` BIGINT(20) NOT NULL, `created_unix` BIGINT(20) NOT NULL, `updated_unix` BIGINT(20) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_notification_repo_id` ON `notification` (`repo_id`);
CREATE INDEX `IDX_notification_commit_id` ON `notification` (`commit_id`);
CREATE INDEX `IDX_notification_created_unix` ON `notification` (`created_unix`);
CREATE INDEX `IDX_notification_updated_unix` ON `notification` (`updated_unix`);
CREATE INDEX `IDX_notification_user_id` ON `notification` (`user_id`);
CREATE INDEX `IDX_notification_status` ON `notification` (`status`);
CREATE INDEX `IDX_notification_source` ON `notification` (`source`);
CREATE INDEX `IDX_notification_issue_id` ON `notification` (`issue_id`);
CREATE INDEX `IDX_notification_updated_by` ON `notification` (`updated_by`);
CREATE TABLE IF NOT EXISTS `issue_user` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `issue_id` BIGINT(20) NULL, `is_read` TINYINT(1) NULL, `is_mentioned` TINYINT(1) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_issue_user_uid` ON `issue_user` (`uid`);
CREATE TABLE IF NOT EXISTS `lfs_meta_object` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `oid` VARCHAR(255) NOT NULL, `size` BIGINT(20) NOT NULL, `repository_id` BIGINT(20) NOT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC ;
CREATE UNIQUE INDEX `UQE_lfs_meta_object_s` ON `lfs_meta_object` (`oid`,`repository_id`);
CREATE INDEX `IDX_lfs_meta_object_repository_id` ON `lfs_meta_object` (`repository_id`);
CREATE INDEX `IDX_lfs_meta_object_oid` ON `lfs_meta_object` (`oid`);
CREATE TABLE IF NOT EXISTS `two_factor` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `secret` VARCHAR(255) NULL, `scratch_salt` VARCHAR(255) NULL, `scratch_hash` VARCHAR(255) NULL, `last_used_passcode` VARCHAR(10) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_two_factor_uid` ON `two_factor` (`uid`);
CREATE INDEX `IDX_two_factor_created_unix` ON `two_factor` (`created_unix`);
CREATE INDEX `IDX_two_factor_updated_unix` ON `two_factor` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `gpg_key` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `owner_id` BIGINT(20) NOT NULL, `key_id` CHAR(16) NOT NULL, `primary_key_id` CHAR(16) NULL, `content` TEXT NOT NULL, `created_unix` BIGINT(20) NULL, `expired_unix` BIGINT(20) NULL, `added_unix` BIGINT(20) NULL, `emails` TEXT NULL, `can_sign` TINYINT(1) NULL, `can_encrypt_comms` TINYINT(1) NULL, `can_encrypt_storage` TINYINT(1) NULL, `can_certify` TINYINT(1) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_gpg_key_owner_id` ON `gpg_key` (`owner_id`);
CREATE INDEX `IDX_gpg_key_key_id` ON `gpg_key` (`key_id`);
CREATE TABLE IF NOT EXISTS `gpg_key_import` (`key_id` CHAR(16) PRIMARY KEY NOT NULL, `content` TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `repo_unit` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `type` INT NULL, `config` TEXT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_repo_unit_s` ON `repo_unit` (`repo_id`,`type`);
CREATE INDEX `IDX_repo_unit_created_unix` ON `repo_unit` (`created_unix`);
CREATE TABLE IF NOT EXISTS `repo_redirect` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `owner_id` BIGINT(20) NULL, `lower_name` VARCHAR(255) NOT NULL, `redirect_repo_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_repo_redirect_s` ON `repo_redirect` (`owner_id`,`lower_name`);
CREATE INDEX `IDX_repo_redirect_lower_name` ON `repo_redirect` (`lower_name`);
CREATE TABLE IF NOT EXISTS `external_login_user` (`external_id` VARCHAR(255) NOT NULL, `user_id` BIGINT(20) NOT NULL, `login_source_id` BIGINT(20) NOT NULL, `raw_data` TEXT NULL, `provider` VARCHAR(25) NULL, `email` VARCHAR(255) NULL, `name` VARCHAR(255) NULL, `first_name` VARCHAR(255) NULL, `last_name` VARCHAR(255) NULL, `nick_name` VARCHAR(255) NULL, `description` VARCHAR(255) NULL, `avatar_url` VARCHAR(255) NULL, `location` VARCHAR(255) NULL, `access_token` TEXT NULL, `access_token_secret` TEXT NULL, `refresh_token` TEXT NULL, `expires_at` DATETIME NULL, PRIMARY KEY ( `external_id`,`login_source_id` )) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_external_login_user_user_id` ON `external_login_user` (`user_id`);
CREATE INDEX `IDX_external_login_user_provider` ON `external_login_user` (`provider`);
CREATE TABLE IF NOT EXISTS `protected_branch` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `branch_name` VARCHAR(255) NULL, `can_push` TINYINT(1) DEFAULT false NOT NULL, `enable_whitelist` TINYINT(1) NULL, `whitelist_user_i_ds` TEXT NULL, `whitelist_team_i_ds` TEXT NULL, `enable_merge_whitelist` TINYINT(1) DEFAULT false NOT NULL, `whitelist_deploy_keys` TINYINT(1) DEFAULT false NOT NULL, `merge_whitelist_user_i_ds` TEXT NULL, `merge_whitelist_team_i_ds` TEXT NULL, `enable_status_check` TINYINT(1) DEFAULT false NOT NULL, `status_check_contexts` TEXT NULL, `enable_approvals_whitelist` TINYINT(1) DEFAULT false NOT NULL, `approvals_whitelist_user_i_ds` TEXT NULL, `approvals_whitelist_team_i_ds` TEXT NULL, `required_approvals` BIGINT(20) DEFAULT 0 NOT NULL, `block_on_rejected_reviews` TINYINT(1) DEFAULT false NOT NULL, `block_on_outdated_branch` TINYINT(1) DEFAULT false NOT NULL, `dismiss_stale_approvals` TINYINT(1) DEFAULT false NOT NULL, `require_signed_commits` TINYINT(1) DEFAULT false NOT NULL, `protected_file_patterns` TEXT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_protected_branch_s` ON `protected_branch` (`repo_id`,`branch_name`);
CREATE TABLE IF NOT EXISTS `user_open_id` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NOT NULL, `uri` VARCHAR(255) NOT NULL, `show` TINYINT(1) DEFAULT false NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_user_open_id_uri` ON `user_open_id` (`uri`);
CREATE INDEX `IDX_user_open_id_uid` ON `user_open_id` (`uid`);
CREATE TABLE IF NOT EXISTS `issue_watch` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NOT NULL, `issue_id` BIGINT(20) NOT NULL, `is_watching` TINYINT(1) NOT NULL, `created_unix` BIGINT(20) NOT NULL, `updated_unix` BIGINT(20) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_issue_watch_watch` ON `issue_watch` (`user_id`,`issue_id`);
CREATE TABLE IF NOT EXISTS `commit_status` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `index` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `state` VARCHAR(7) NOT NULL, `sha` VARCHAR(64) NOT NULL, `target_url` TEXT NULL, `description` TEXT NULL, `context_hash` CHAR(40) NULL, `context` TEXT NULL, `creator_id` BIGINT(20) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_commit_status_repo_sha_index` ON `commit_status` (`index`,`repo_id`,`sha`);
CREATE INDEX `IDX_commit_status_index` ON `commit_status` (`index`);
CREATE INDEX `IDX_commit_status_repo_id` ON `commit_status` (`repo_id`);
CREATE INDEX `IDX_commit_status_sha` ON `commit_status` (`sha`);
CREATE INDEX `IDX_commit_status_context_hash` ON `commit_status` (`context_hash`);
CREATE INDEX `IDX_commit_status_created_unix` ON `commit_status` (`created_unix`);
CREATE INDEX `IDX_commit_status_updated_unix` ON `commit_status` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `stopwatch` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `issue_id` BIGINT(20) NULL, `user_id` BIGINT(20) NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_stopwatch_issue_id` ON `stopwatch` (`issue_id`);
CREATE INDEX `IDX_stopwatch_user_id` ON `stopwatch` (`user_id`);
CREATE TABLE IF NOT EXISTS `tracked_time` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `issue_id` BIGINT(20) NULL, `user_id` BIGINT(20) NULL, `created_unix` BIGINT(20) NULL, `time` BIGINT(20) NOT NULL, `deleted` TINYINT(1) DEFAULT false NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_tracked_time_issue_id` ON `tracked_time` (`issue_id`);
CREATE INDEX `IDX_tracked_time_user_id` ON `tracked_time` (`user_id`);
CREATE TABLE IF NOT EXISTS `deleted_branch` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NOT NULL, `name` VARCHAR(255) NOT NULL, `commit` VARCHAR(255) NOT NULL, `deleted_by_id` BIGINT(20) NULL, `deleted_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_deleted_branch_s` ON `deleted_branch` (`repo_id`,`name`,`commit`);
CREATE INDEX `IDX_deleted_branch_repo_id` ON `deleted_branch` (`repo_id`);
CREATE INDEX `IDX_deleted_branch_deleted_by_id` ON `deleted_branch` (`deleted_by_id`);
CREATE INDEX `IDX_deleted_branch_deleted_unix` ON `deleted_branch` (`deleted_unix`);
CREATE TABLE IF NOT EXISTS `repo_indexer_status` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NULL, `commit_sha` VARCHAR(40) NULL, `indexer_type` INT DEFAULT 0 NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_repo_indexer_status_s` ON `repo_indexer_status` (`repo_id`,`indexer_type`);
CREATE TABLE IF NOT EXISTS `issue_dependency` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NOT NULL, `issue_id` BIGINT(20) NOT NULL, `dependency_id` BIGINT(20) NOT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_issue_dependency_issue_dependency` ON `issue_dependency` (`issue_id`,`dependency_id`);
CREATE TABLE IF NOT EXISTS `lfs_lock` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NOT NULL, `owner_id` BIGINT(20) NOT NULL, `path` TEXT NULL, `created` DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_lfs_lock_repo_id` ON `lfs_lock` (`repo_id`);
CREATE INDEX `IDX_lfs_lock_owner_id` ON `lfs_lock` (`owner_id`);
CREATE TABLE IF NOT EXISTS `reaction` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` VARCHAR(255) NOT NULL, `issue_id` BIGINT(20) NOT NULL, `comment_id` BIGINT(20) NULL, `user_id` BIGINT(20) NOT NULL, `original_author_id` BIGINT(20) DEFAULT 0 NOT NULL, `original_author` VARCHAR(255) NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_reaction_s` ON `reaction` (`type`,`issue_id`,`comment_id`,`user_id`,`original_author_id`);
CREATE INDEX `IDX_reaction_created_unix` ON `reaction` (`created_unix`);
CREATE INDEX `IDX_reaction_type` ON `reaction` (`type`);
CREATE INDEX `IDX_reaction_issue_id` ON `reaction` (`issue_id`);
CREATE INDEX `IDX_reaction_comment_id` ON `reaction` (`comment_id`);
CREATE INDEX `IDX_reaction_user_id` ON `reaction` (`user_id`);
CREATE INDEX `IDX_reaction_original_author_id` ON `reaction` (`original_author_id`);
CREATE TABLE IF NOT EXISTS `issue_assignees` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `assignee_id` BIGINT(20) NULL, `issue_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_issue_assignees_assignee_id` ON `issue_assignees` (`assignee_id`);
CREATE INDEX `IDX_issue_assignees_issue_id` ON `issue_assignees` (`issue_id`);
CREATE TABLE IF NOT EXISTS `u2f_registration` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR(255) NULL, `user_id` BIGINT(20) NULL, `raw` BLOB NULL, `counter` BIGINT(20) NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_u2f_registration_created_unix` ON `u2f_registration` (`created_unix`);
CREATE INDEX `IDX_u2f_registration_updated_unix` ON `u2f_registration` (`updated_unix`);
CREATE INDEX `IDX_u2f_registration_user_id` ON `u2f_registration` (`user_id`);
CREATE TABLE IF NOT EXISTS `team_unit` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `org_id` BIGINT(20) NULL, `team_id` BIGINT(20) NULL, `type` INT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_team_unit_s` ON `team_unit` (`team_id`,`type`);
CREATE INDEX `IDX_team_unit_org_id` ON `team_unit` (`org_id`);
CREATE TABLE IF NOT EXISTS `review` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `type` INT NULL, `reviewer_id` BIGINT(20) NULL, `original_author` VARCHAR(255) NULL, `original_author_id` BIGINT(20) NULL, `issue_id` BIGINT(20) NULL, `content` TEXT NULL, `official` TINYINT(1) DEFAULT false NOT NULL, `commit_id` VARCHAR(40) NULL, `stale` TINYINT(1) DEFAULT false NOT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_review_reviewer_id` ON `review` (`reviewer_id`);
CREATE INDEX `IDX_review_issue_id` ON `review` (`issue_id`);
CREATE INDEX `IDX_review_created_unix` ON `review` (`created_unix`);
CREATE INDEX `IDX_review_updated_unix` ON `review` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `oauth2_application` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `uid` BIGINT(20) NULL, `name` VARCHAR(255) NULL, `client_id` VARCHAR(255) NULL, `client_secret` VARCHAR(255) NULL, `redirect_uris` TEXT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_oauth2_application_client_id` ON `oauth2_application` (`client_id`);
CREATE INDEX `IDX_oauth2_application_uid` ON `oauth2_application` (`uid`);
CREATE INDEX `IDX_oauth2_application_created_unix` ON `oauth2_application` (`created_unix`);
CREATE INDEX `IDX_oauth2_application_updated_unix` ON `oauth2_application` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `oauth2_authorization_code` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `grant_id` BIGINT(20) NULL, `code` VARCHAR(255) NULL, `code_challenge` VARCHAR(255) NULL, `code_challenge_method` VARCHAR(255) NULL, `redirect_uri` VARCHAR(255) NULL, `valid_until` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_oauth2_authorization_code_code` ON `oauth2_authorization_code` (`code`);
CREATE INDEX `IDX_oauth2_authorization_code_valid_until` ON `oauth2_authorization_code` (`valid_until`);
CREATE TABLE IF NOT EXISTS `oauth2_grant` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `user_id` BIGINT(20) NULL, `application_id` BIGINT(20) NULL, `counter` BIGINT(20) DEFAULT 1 NOT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_oauth2_grant_user_application` ON `oauth2_grant` (`user_id`,`application_id`);
CREATE INDEX `IDX_oauth2_grant_user_id` ON `oauth2_grant` (`user_id`);
CREATE INDEX `IDX_oauth2_grant_application_id` ON `oauth2_grant` (`application_id`);
CREATE TABLE IF NOT EXISTS `task` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `doer_id` BIGINT(20) NULL, `owner_id` BIGINT(20) NULL, `repo_id` BIGINT(20) NULL, `type` INT NULL, `status` INT NULL, `start_time` BIGINT(20) NULL, `end_time` BIGINT(20) NULL, `payload_content` TEXT NULL, `errors` TEXT NULL, `created` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE INDEX `IDX_task_doer_id` ON `task` (`doer_id`);
CREATE INDEX `IDX_task_owner_id` ON `task` (`owner_id`);
CREATE INDEX `IDX_task_repo_id` ON `task` (`repo_id`);
CREATE INDEX `IDX_task_status` ON `task` (`status`);
CREATE TABLE IF NOT EXISTS `language_stat` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `repo_id` BIGINT(20) NOT NULL, `commit_id` VARCHAR(255) NULL, `is_primary` TINYINT(1) NULL, `language` VARCHAR(30) NOT NULL, `percentage` NUMERIC(5,2) DEFAULT 0 NOT NULL, `created_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_language_stat_s` ON `language_stat` (`repo_id`,`language`);
CREATE INDEX `IDX_language_stat_language` ON `language_stat` (`language`);
CREATE INDEX `IDX_language_stat_created_unix` ON `language_stat` (`created_unix`);
CREATE INDEX `IDX_language_stat_repo_id` ON `language_stat` (`repo_id`);
CREATE TABLE IF NOT EXISTS `email_hash` (`hash` VARCHAR(32) PRIMARY KEY NOT NULL, `email` VARCHAR(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_email_hash_email` ON `email_hash` (`email`);
CREATE TABLE IF NOT EXISTS `topic` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR(25) NULL, `repo_count` INT NULL, `created_unix` BIGINT(20) NULL, `updated_unix` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_topic_name` ON `topic` (`name`);
CREATE INDEX `IDX_topic_created_unix` ON `topic` (`created_unix`);
CREATE INDEX `IDX_topic_updated_unix` ON `topic` (`updated_unix`);
CREATE TABLE IF NOT EXISTS `repo_topic` (`repo_id` BIGINT(20) NULL, `topic_id` BIGINT(20) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8 ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX `UQE_repo_topic_s` ON `repo_topic` (`repo_id`,`topic_id`);

