version: '3.6'

volumes:
  redis-host1:
  redis-host2:
  redis-host3:
  redis-host4:
  redis-host5:
  redis-host6:
  redis-haproxy:

services:

  redis-1:
    network_mode: host
    container_name: redis-1
    build: redis-1
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7000:7000
    volumes:
      - redis-host1:/data

  redis-2:
    network_mode: host
    container_name: redis-2
    build: redis-2
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7001:7001
    volumes:
      - redis-host2:/data
    depends_on:
      - redis-1

  redis-3:
    network_mode: host
    container_name: redis-3
    build: redis-3
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7002:7002
    volumes:
      - redis-host3:/data
    depends_on:
      - redis-2

  redis-4:
    network_mode: host
    container_name: redis-4
    build: redis-4
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7003:7003
    volumes:
      - redis-host4:/data
    depends_on:
      - redis-3

  redis-5:
    network_mode: host
    container_name: redis-5
    build: redis-5
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7004:7004
    volumes:
      - redis-host5:/data
    depends_on:
      - redis-4

  redis-6:
    network_mode: host
    container_name: redis-6
    build: redis-6
    command: redis-server /etc/redis/redis.conf
    ports:
      - 7005:7005
    volumes:
      - redis-host6:/data
    depends_on:
      - redis-5


  haproxy-1:
    container_name: haproxy-1
    build: haproxy
    ports:
      - 9000:9000
    volumes:
      - redis-haproxy:/data
    depends_on:
      - redis-6